/*
###############################################################
#  Generated by:      Cadence Encounter 14.28-s033_1
#  OS:                Linux x86_64(Host ID cobalt.clear.rice.edu)
#  Generated on:      Wed Feb 28 12:45:17 2018
#  Design:            top_module
#  Command:           saveNetlist final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : N-2017.09-SP2
// Date      : Wed Feb 28 12:15:55 2018
/////////////////////////////////////////////////////////////
module top_module (
	in_clka, 
	in_clkb, 
	in_restart, 
	in_load, 
	in_Not, 
	con_loadData, 
	con_notData, 
	con_clearData, 
	in_data0, 
	in_data1, 
	in_data2, 
	in_data3, 
	out_DO0, 
	out_DO1, 
	out_DO2, 
	out_DO3, 
	out_state);
   input in_clka;
   input in_clkb;
   input in_restart;
   input in_load;
   input in_Not;
   output con_loadData;
   output con_notData;
   output con_clearData;
   input in_data0;
   input in_data1;
   input in_data2;
   input in_data3;
   output out_DO0;
   output out_DO1;
   output out_DO2;
   output out_DO3;
   output [2:0] out_state;

   // Internal wires
   wire \U2/n18 ;
   wire \U2/n17 ;
   wire \U2/n16 ;
   wire \U2/n15 ;
   wire \U2/n14 ;
   wire \U2/n13 ;
   wire \U2/n12 ;
   wire \U2/n11 ;
   wire \U2/n10 ;
   wire \U2/n9 ;
   wire \U2/n8 ;
   wire \U2/n7 ;
   wire \U2/n6 ;
   wire \U2/n5 ;
   wire \U2/n4 ;
   wire \U2/n3 ;
   wire \U2/n2 ;
   wire \U2/n1 ;
   wire \U1/n18 ;
   wire \U1/n17 ;
   wire \U1/n16 ;
   wire \U1/n15 ;
   wire \U1/n14 ;
   wire \U1/n13 ;
   wire \U1/n12 ;
   wire \U1/n11 ;
   wire \U1/n10 ;
   wire \U1/n9 ;
   wire \U1/n8 ;
   wire \U1/n7 ;
   wire \U1/n6 ;
   wire \U1/n5 ;
   wire \U1/n4 ;
   wire \U1/n3 ;
   wire \U1/n2 ;
   wire \U1/n1 ;
   wire \U1/N56 ;
   wire \U1/N55 ;
   wire \U1/N54 ;
   wire \U1/N41 ;
   wire \U1/N40 ;
   wire \U1/N39 ;
   wire [2:0] \U1/next_state ;

   NAND3X1 \U2/U20  (.Y(\U2/n14 ),
	.C(con_notData),
	.B(\U2/n5 ),
	.A(\U2/n6 ));
   NAND3X1 \U2/U19  (.Y(\U2/n10 ),
	.C(\U2/n14 ),
	.B(\U2/n5 ),
	.A(\U2/n6 ));
   AOI22X1 \U2/U18  (.Y(\U2/n13 ),
	.D(con_loadData),
	.C(in_data3),
	.B(\U2/n1 ),
	.A(\U2/n4 ));
   OAI21X1 \U2/U17  (.Y(\U2/n18 ),
	.C(\U2/n13 ),
	.B(\U2/n1 ),
	.A(\U2/n10 ));
   AOI22X1 \U2/U16  (.Y(\U2/n12 ),
	.D(con_loadData),
	.C(in_data0),
	.B(\U2/n2 ),
	.A(\U2/n4 ));
   OAI21X1 \U2/U15  (.Y(\U2/n17 ),
	.C(\U2/n12 ),
	.B(\U2/n2 ),
	.A(\U2/n10 ));
   AOI22X1 \U2/U14  (.Y(\U2/n11 ),
	.D(con_loadData),
	.C(in_data1),
	.B(\U2/n3 ),
	.A(\U2/n4 ));
   OAI21X1 \U2/U13  (.Y(\U2/n16 ),
	.C(\U2/n11 ),
	.B(\U2/n3 ),
	.A(\U2/n10 ));
   XNOR2X1 \U2/U12  (.Y(\U2/n7 ),
	.B(out_DO2),
	.A(con_notData));
   NAND2X1 \U2/U11  (.Y(\U2/n8 ),
	.B(\U2/n5 ),
	.A(\U2/n6 ));
   NAND2X1 \U2/U10  (.Y(\U2/n9 ),
	.B(in_data2),
	.A(con_loadData));
   OAI21X1 \U2/U9  (.Y(\U2/n15 ),
	.C(\U2/n9 ),
	.B(\U2/n8 ),
	.A(\U2/n7 ));
   INVX2 \U2/U8  (.Y(\U2/n6 ),
	.A(con_clearData));
   INVX2 \U2/U7  (.Y(\U2/n5 ),
	.A(con_loadData));
   INVX2 \U2/U6  (.Y(\U2/n4 ),
	.A(\U2/n14 ));
   INVX2 \U2/U5  (.Y(\U2/n3 ),
	.A(out_DO1));
   INVX2 \U2/U4  (.Y(\U2/n2 ),
	.A(out_DO0));
   INVX2 \U2/U3  (.Y(\U2/n1 ),
	.A(out_DO3));
   DFFPOSX1 \U2/DO2_reg  (.Q(out_DO2),
	.D(\U2/n15 ),
	.CLK(in_clka));
   DFFPOSX1 \U2/DO1_reg  (.Q(out_DO1),
	.D(\U2/n16 ),
	.CLK(in_clka));
   DFFPOSX1 \U2/DO0_reg  (.Q(out_DO0),
	.D(\U2/n17 ),
	.CLK(in_clka));
   DFFPOSX1 \U2/DO3_reg  (.Q(out_DO3),
	.D(\U2/n18 ),
	.CLK(in_clka));
   NOR2X1 \U1/U26  (.Y(\U1/n18 ),
	.B(out_state[0]),
	.A(out_state[2]));
   NAND2X1 \U1/U25  (.Y(\U1/n16 ),
	.B(\U1/n5 ),
	.A(out_state[0]));
   AOI22X1 \U1/U24  (.Y(\U1/n17 ),
	.D(\U1/n16 ),
	.C(in_load),
	.B(in_Not),
	.A(\U1/n18 ));
   XOR2X1 \U1/U23  (.Y(\U1/n12 ),
	.B(out_state[1]),
	.A(out_state[0]));
   OAI21X1 \U1/U22  (.Y(\U1/N39 ),
	.C(\U1/n6 ),
	.B(\U1/n12 ),
	.A(\U1/n17 ));
   OAI21X1 \U1/U21  (.Y(\U1/n15 ),
	.C(in_load),
	.B(\U1/n12 ),
	.A(\U1/n4 ));
   NAND2X1 \U1/U20  (.Y(\U1/N40 ),
	.B(\U1/n6 ),
	.A(\U1/n15 ));
   OAI21X1 \U1/U19  (.Y(\U1/n14 ),
	.C(\U1/n5 ),
	.B(\U1/n8 ),
	.A(out_state[0]));
   NAND2X1 \U1/U18  (.Y(\U1/n13 ),
	.B(\U1/n7 ),
	.A(\U1/n14 ));
   OAI21X1 \U1/U17  (.Y(\U1/N41 ),
	.C(\U1/n6 ),
	.B(\U1/n13 ),
	.A(\U1/n12 ));
   NAND2X1 \U1/U16  (.Y(\U1/n11 ),
	.B(\U1/next_state [0]),
	.A(\U1/next_state [2]));
   NOR2X1 \U1/U15  (.Y(\U1/N54 ),
	.B(\U1/n11 ),
	.A(\U1/n2 ));
   NAND2X1 \U1/U14  (.Y(\U1/n10 ),
	.B(\U1/n2 ),
	.A(\U1/next_state [0]));
   NOR2X1 \U1/U13  (.Y(\U1/N55 ),
	.B(\U1/n10 ),
	.A(\U1/n1 ));
   NAND2X1 \U1/U12  (.Y(\U1/n9 ),
	.B(\U1/n1 ),
	.A(\U1/n2 ));
   NOR2X1 \U1/U11  (.Y(\U1/N56 ),
	.B(\U1/n9 ),
	.A(\U1/n3 ));
   INVX2 \U1/U10  (.Y(\U1/n8 ),
	.A(in_Not));
   INVX2 \U1/U9  (.Y(\U1/n7 ),
	.A(in_load));
   INVX2 \U1/U8  (.Y(\U1/n6 ),
	.A(in_restart));
   INVX2 \U1/U7  (.Y(\U1/n5 ),
	.A(out_state[2]));
   INVX2 \U1/U6  (.Y(\U1/n4 ),
	.A(\U1/n16 ));
   INVX2 \U1/U5  (.Y(\U1/n3 ),
	.A(\U1/next_state [0]));
   INVX2 \U1/U4  (.Y(\U1/n2 ),
	.A(\U1/next_state [1]));
   INVX2 \U1/U3  (.Y(\U1/n1 ),
	.A(\U1/next_state [2]));
   DFFPOSX1 \U1/loadData_reg  (.Q(con_loadData),
	.D(\U1/N56 ),
	.CLK(in_clkb));
   DFFPOSX1 \U1/notData_reg  (.Q(con_notData),
	.D(\U1/N55 ),
	.CLK(in_clkb));
   DFFPOSX1 \U1/clearData_reg  (.Q(con_clearData),
	.D(\U1/N54 ),
	.CLK(in_clkb));
   DFFPOSX1 \U1/next_state_reg[0]  (.Q(\U1/next_state [0]),
	.D(\U1/N39 ),
	.CLK(in_clka));
   DFFPOSX1 \U1/state_reg[1]  (.Q(out_state[1]),
	.D(\U1/next_state [1]),
	.CLK(in_clkb));
   DFFPOSX1 \U1/next_state_reg[1]  (.Q(\U1/next_state [1]),
	.D(\U1/N40 ),
	.CLK(in_clka));
   DFFPOSX1 \U1/state_reg[2]  (.Q(out_state[2]),
	.D(\U1/next_state [2]),
	.CLK(in_clkb));
   DFFPOSX1 \U1/next_state_reg[2]  (.Q(\U1/next_state [2]),
	.D(\U1/N41 ),
	.CLK(in_clka));
   DFFPOSX1 \U1/state_reg[0]  (.Q(out_state[0]),
	.D(\U1/next_state [0]),
	.CLK(in_clkb));
endmodule

